FROM heroku/heroku:16-build as build

COPY . /app
WORKDIR /app

# Setup buildpack
RUN mkdir -p /tmp/buildpack/heroku/go /tmp/build_cache /tmp/env
# RUN curl https://codon-buildpacks.s3.amazonaws.com/buildpacks/heroku/go.tgz | tar xz -C /tmp/buildpack/heroku/go

#Execute Buildpack
#RUN STACK=heroku-16 /tmp/buildpack/heroku/go/bin/compile /app /tmp/build_cache /tmp/env

# Prepare final, minimal image
FROM heroku/heroku:16

# COPY --from=build /app /app
COPY ./line-todo /app/bin/line-todo
COPY ./line-todo-0f1e608bd17a.json /app/line-todo-0f1e608bd17a.json
ENV HOME /app 192.168.43.131
WORKDIR /app
RUN useradd -m heroku
USER heroku
CMD /app/bin/line-todo